# Generated by Django 2.2.2 on 2024-10-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkin_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout_date',
            field=models.CharField(max_length=50),
        ),
    ]
