# Generated by Django 2.2.2 on 2024-10-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_auto_20241025_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_amount',
            field=models.PositiveIntegerField(default=3000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='tariff',
            field=models.PositiveIntegerField(),
        ),
    ]
